apiVersion: v1
kind: Service
metadata:
  name: automatethings-py
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: automatethings-py
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatethings-py
  labels:
    app: automatethings-py
spec:
  replicas: 5
  selector:
    matchLabels:
      app: automatethings-py
  template:
    metadata:
      labels:
        app: automatethings-py
    spec:
      containers:
      - name: automatethings-py
        image: 258001553249.dkr.ecr.us-west-2.amazonaws.com/ecrstack-us-west-2-ecrdemoxyzec8e3b3e-swseynlkuayc:latest
        ports:
        - containerPort: 80
